spring:
  application:
    name: eureka-client
server:
  port: 8889
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30

  client:
    service-url:
      defaultZone: http://localhost:8888/eureka