spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.16.70:3306/sharding_order?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
        username: root
        password: abcABC@123
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://172.16.16.71:3306/sharding_order?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
        username: root
        password: abcABC@123
    sharding:
      tables:
        t_order:
          actual-data-nodes: ds$->{0..1}.t_order_$->{1..2}
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: ds$->{user_id % 2}
          table-strategy:
            standard:
              sharding-column: id
              precise-algorithm-class-name: com.tristeza.shardingjdbc.sharding.UUIDSharding
          key-generator:
            column: id
            type: UUID
      broadcast-tables: area
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.tristeza.shardingjdbc.model   # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl